apiVersion: v1
kind: Pod
metadata:
  # replicas: "1"
  name: "mypod3"
  labels: 
    app: web
    dc: US
    team: test
spec:
  containers:
  - name: "c1"
    image: "anand1501/apache-server-php:v1"
    ports:
    - containerPort: 80
    
    