apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydb
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  strategy: {}
  template:
    metadata: 
      labels:
        app: mydb
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsec
              key: pwd
        - name: MYSQL_DATABASE
          value: mysqldb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dbsec
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsec
              key: pwd